### PR TITLE
Fix grammatical typo in readme

### PR DESCRIPTION
**Pull request by singhay**

### CODE REVIEW

**Comment by singhay** [comment]
Updated CLA!

**Comment by singhay** [comment]
I signed it!

**Comment by singhay** [comment]
Done

**Comment by singhay** [comment]
Hi, I'm not able to get CLA verified no matter what.

**Comment by Splaktar** [comment]
Thank you for pointing this out. Fixed in https://github.com/angular/material-start/commit/f5aa0d277fb340b53958e54213d874f27d293b2f.

**Pull request closed without merging**
