### PR TITLE
Converting 'git+ssh' dependency to 'npm' dependency.

### PR DESCRIPTION
**Pull request by zainfathoni**
It fixed 'npm install' error on my machine.

25-8-2016 8-01-56 am

### CODE REVIEW

**Comment by ThomasBurleson** [comment]
@zainfathoni - 👍 
@topherfangio - can you merge this into all the branches. Thx.

**Comment by zainfathoni** [comment]
@googlebot - I signed it! :white_check_mark: 
@ThomasBurleson - Thanks! :smile:

**Comment by topherfangio** [comment]
Merged via 2e184275741087c8f5dbc49ba5c18a096de9126f.

**Comment by topherfangio** [comment]
Also merged into master via d98f7d4570ee3fe1afe465bceb65e9b8d04371b0.

**Pull request closed without merging**
