### PR TITLE
fix babel issue "Unknown option: direct.0" [RESOLVED]

### PR DESCRIPTION
**Pull request by angelomichel**
Fix for issue: https://github.com/angular/material-start/issues/163

### CODE REVIEW

**Comment by marconi1992** [comment]
This fix works for me, Thanks @angelomichel

**Comment by EladBezalel** [comment]
@angelomichel can you rebase?

**Comment by angelomichel** [comment]
I signed it!

@EladBezalel I resolved the conflicts.

**Comment by EladBezalel** [comment]
@angelomichel can you please squash the commits together?

**Comment by angelomichel** [comment]
Hey @EladBezalel.  

I double-checked my commits and the latest version. Turns out the current master version uses traceur which solves the issue. For future reference, anyone who has this issue, just update material-start.

I will close this PR.

**Pull request closed without merging**
