### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by r0zar**
Fix markdown.

### CODE REVIEW

**Comment by r0zar** [comment]
I signed it!

**Comment by EladBezalel** [comment]
@r0zar what's the purpose of this change?

**Comment by r0zar** [comment]
To fix a broken image link in the docs.

**Comment by EladBezalel** [comment]
I can see totally fine.. can you attach a screenshot?

**Comment by r0zar** [comment]
Check the angular:es6-tutorial branch. It's the branch people are linked to from the popular https://material.angularjs.org/latest/getting-started docs for ES6.

**Comment by r0zar** [comment]
That particular image link is broken on a few of the steps of the tutorial, but the initial page after being linked from the official docs is probably most important.

**Comment by r0zar** [comment]
Thanks Elad!

**Comment by EladBezalel** [comment]
@r0zar thank you :)

**Pull request merged**
